// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// model.cpp
SEXP dust_model_alloc(cpp11::list r_pars, bool pars_multi, size_t step, cpp11::sexp r_n_particles, size_t n_threads, cpp11::sexp r_seed, bool deterministic, cpp11::sexp device_config);
extern "C" SEXP _gonovaxdust_dust_model_alloc(SEXP r_pars, SEXP pars_multi, SEXP step, SEXP r_n_particles, SEXP n_threads, SEXP r_seed, SEXP deterministic, SEXP device_config) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<bool>>(pars_multi), cpp11::as_cpp<cpp11::decay_t<size_t>>(step), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<size_t>>(n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<bool>>(deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(device_config)));
  END_CPP11
}
// model.cpp
SEXP dust_model_run(SEXP ptr, size_t step_end, bool device);
extern "C" SEXP _gonovaxdust_dust_model_run(SEXP ptr, SEXP step_end, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_run(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<size_t>>(step_end), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// model.cpp
SEXP dust_model_simulate(SEXP ptr, cpp11::sexp step_end, bool device);
extern "C" SEXP _gonovaxdust_dust_model_simulate(SEXP ptr, SEXP step_end, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_simulate(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(step_end), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// model.cpp
SEXP dust_model_set_index(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _gonovaxdust_dust_model_set_index(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_set_index(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index)));
  END_CPP11
}
// model.cpp
SEXP dust_model_update_state(SEXP ptr, SEXP r_pars, SEXP r_state, SEXP r_step, SEXP r_set_initial_state);
extern "C" SEXP _gonovaxdust_dust_model_update_state(SEXP ptr, SEXP r_pars, SEXP r_state, SEXP r_step, SEXP r_set_initial_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_update_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_pars), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_state), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_step), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_set_initial_state)));
  END_CPP11
}
// model.cpp
SEXP dust_model_state(SEXP ptr, SEXP r_index);
extern "C" SEXP _gonovaxdust_dust_model_state(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_index)));
  END_CPP11
}
// model.cpp
size_t dust_model_step(SEXP ptr);
extern "C" SEXP _gonovaxdust_dust_model_step(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_step(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr)));
  END_CPP11
}
// model.cpp
void dust_model_reorder(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _gonovaxdust_dust_model_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    dust_model_reorder(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index));
    return R_NilValue;
  END_CPP11
}
// model.cpp
SEXP dust_model_resample(SEXP ptr, cpp11::doubles r_weights);
extern "C" SEXP _gonovaxdust_dust_model_resample(SEXP ptr, SEXP r_weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_resample(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(r_weights)));
  END_CPP11
}
// model.cpp
SEXP dust_model_rng_state(SEXP ptr, bool first_only, bool last_only);
extern "C" SEXP _gonovaxdust_dust_model_rng_state(SEXP ptr, SEXP first_only, SEXP last_only) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_rng_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(first_only), cpp11::as_cpp<cpp11::decay_t<bool>>(last_only)));
  END_CPP11
}
// model.cpp
SEXP dust_model_set_rng_state(SEXP ptr, cpp11::raws rng_state);
extern "C" SEXP _gonovaxdust_dust_model_set_rng_state(SEXP ptr, SEXP rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_set_rng_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::raws>>(rng_state)));
  END_CPP11
}
// model.cpp
SEXP dust_model_set_data(SEXP ptr, cpp11::list data);
extern "C" SEXP _gonovaxdust_dust_model_set_data(SEXP ptr, SEXP data) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_set_data(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(data)));
  END_CPP11
}
// model.cpp
SEXP dust_model_compare_data(SEXP ptr, bool device);
extern "C" SEXP _gonovaxdust_dust_model_compare_data(SEXP ptr, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_compare_data(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// model.cpp
SEXP dust_model_filter(SEXP ptr, bool save_trajectories, cpp11::sexp step_snapshot, bool device);
extern "C" SEXP _gonovaxdust_dust_model_filter(SEXP ptr, SEXP save_trajectories, SEXP step_snapshot, SEXP device) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_filter(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(step_snapshot), cpp11::as_cpp<cpp11::decay_t<bool>>(device)));
  END_CPP11
}
// model.cpp
cpp11::sexp dust_model_capabilities();
extern "C" SEXP _gonovaxdust_dust_model_capabilities() {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_capabilities());
  END_CPP11
}
// model.cpp
void dust_model_set_n_threads(SEXP ptr, int n_threads);
extern "C" SEXP _gonovaxdust_dust_model_set_n_threads(SEXP ptr, SEXP n_threads) {
  BEGIN_CPP11
    dust_model_set_n_threads(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<int>>(n_threads));
    return R_NilValue;
  END_CPP11
}
// model.cpp
int dust_model_n_state(SEXP ptr);
extern "C" SEXP _gonovaxdust_dust_model_n_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_n_state(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr)));
  END_CPP11
}
// model.cpp
cpp11::sexp dust_model_device_info();
extern "C" SEXP _gonovaxdust_dust_model_device_info() {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_model_device_info());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_gonovaxdust_dust_model_alloc",         (DL_FUNC) &_gonovaxdust_dust_model_alloc,         8},
    {"_gonovaxdust_dust_model_capabilities",  (DL_FUNC) &_gonovaxdust_dust_model_capabilities,  0},
    {"_gonovaxdust_dust_model_compare_data",  (DL_FUNC) &_gonovaxdust_dust_model_compare_data,  2},
    {"_gonovaxdust_dust_model_device_info",   (DL_FUNC) &_gonovaxdust_dust_model_device_info,   0},
    {"_gonovaxdust_dust_model_filter",        (DL_FUNC) &_gonovaxdust_dust_model_filter,        4},
    {"_gonovaxdust_dust_model_n_state",       (DL_FUNC) &_gonovaxdust_dust_model_n_state,       1},
    {"_gonovaxdust_dust_model_reorder",       (DL_FUNC) &_gonovaxdust_dust_model_reorder,       2},
    {"_gonovaxdust_dust_model_resample",      (DL_FUNC) &_gonovaxdust_dust_model_resample,      2},
    {"_gonovaxdust_dust_model_rng_state",     (DL_FUNC) &_gonovaxdust_dust_model_rng_state,     3},
    {"_gonovaxdust_dust_model_run",           (DL_FUNC) &_gonovaxdust_dust_model_run,           3},
    {"_gonovaxdust_dust_model_set_data",      (DL_FUNC) &_gonovaxdust_dust_model_set_data,      2},
    {"_gonovaxdust_dust_model_set_index",     (DL_FUNC) &_gonovaxdust_dust_model_set_index,     2},
    {"_gonovaxdust_dust_model_set_n_threads", (DL_FUNC) &_gonovaxdust_dust_model_set_n_threads, 2},
    {"_gonovaxdust_dust_model_set_rng_state", (DL_FUNC) &_gonovaxdust_dust_model_set_rng_state, 2},
    {"_gonovaxdust_dust_model_simulate",      (DL_FUNC) &_gonovaxdust_dust_model_simulate,      3},
    {"_gonovaxdust_dust_model_state",         (DL_FUNC) &_gonovaxdust_dust_model_state,         2},
    {"_gonovaxdust_dust_model_step",          (DL_FUNC) &_gonovaxdust_dust_model_step,          1},
    {"_gonovaxdust_dust_model_update_state",  (DL_FUNC) &_gonovaxdust_dust_model_update_state,  5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_gonovaxdust(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
