# Generated by cpp11: do not edit by hand

dust_model_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, device_config) {
  .Call(`_gonovaxdust_dust_model_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, device_config)
}

dust_model_run <- function(ptr, step_end, device, deterministic) {
  .Call(`_gonovaxdust_dust_model_run`, ptr, step_end, device, deterministic)
}

dust_model_simulate <- function(ptr, step_end, device, deterministic) {
  .Call(`_gonovaxdust_dust_model_simulate`, ptr, step_end, device, deterministic)
}

dust_model_set_index <- function(ptr, r_index) {
  .Call(`_gonovaxdust_dust_model_set_index`, ptr, r_index)
}

dust_model_set_state <- function(ptr, r_state, r_step, deterministic) {
  .Call(`_gonovaxdust_dust_model_set_state`, ptr, r_state, r_step, deterministic)
}

dust_model_reset <- function(ptr, r_pars, step) {
  .Call(`_gonovaxdust_dust_model_reset`, ptr, r_pars, step)
}

dust_model_state <- function(ptr, r_index) {
  .Call(`_gonovaxdust_dust_model_state`, ptr, r_index)
}

dust_model_step <- function(ptr) {
  .Call(`_gonovaxdust_dust_model_step`, ptr)
}

dust_model_reorder <- function(ptr, r_index) {
  invisible(.Call(`_gonovaxdust_dust_model_reorder`, ptr, r_index))
}

dust_model_resample <- function(ptr, r_weights) {
  .Call(`_gonovaxdust_dust_model_resample`, ptr, r_weights)
}

dust_model_set_pars <- function(ptr, r_pars) {
  .Call(`_gonovaxdust_dust_model_set_pars`, ptr, r_pars)
}

dust_model_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_gonovaxdust_dust_model_rng_state`, ptr, first_only, last_only)
}

dust_model_set_rng_state <- function(ptr, rng_state) {
  .Call(`_gonovaxdust_dust_model_set_rng_state`, ptr, rng_state)
}

dust_model_set_data <- function(ptr, data) {
  .Call(`_gonovaxdust_dust_model_set_data`, ptr, data)
}

dust_model_compare_data <- function(ptr, device) {
  .Call(`_gonovaxdust_dust_model_compare_data`, ptr, device)
}

dust_model_filter <- function(ptr, save_trajectories, step_snapshot, device) {
  .Call(`_gonovaxdust_dust_model_filter`, ptr, save_trajectories, step_snapshot, device)
}

dust_model_capabilities <- function() {
  .Call(`_gonovaxdust_dust_model_capabilities`)
}

dust_model_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_gonovaxdust_dust_model_set_n_threads`, ptr, n_threads))
}

dust_model_n_state <- function(ptr) {
  .Call(`_gonovaxdust_dust_model_n_state`, ptr)
}

dust_model_device_info <- function() {
  .Call(`_gonovaxdust_dust_model_device_info`)
}
